---
  - name: setup plugins dir
    shell: >
      mkdir -p "{{ ansible_env.HOME }}"/.rbenv/plugins
  - name: rbenv | clone ruby-build repo
    git: 
      repo: https://github.com/rbenv/ruby-build.git 
      dest: ~/.rbenv/plugins/ruby-build

  - name: rbenv | check ruby 2.5.3 installed
    shell: cd; bash -lc "rbenv versions | grep 2.5.2"
    register: ruby_installed
    ignore_errors: yes

  - name: rbenv | install ruby
    shell: cd; bash -lc "rbenv install 2.5.3"
    when: ruby_installed is failed

  - name: rbenv | set global ruby version
    shell: cd; bash -lc "rbenv global 2.5.3"