---
- hosts: 192.168.33.10
  remote_user: vagrant
  tasks:
    - name: Install Postgresql
      become: yes
      apt:
        pkg:
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present