---
  - name: Install Postgresql
    become: yes
    apt:
      pkg:
        - postgresql
        - postgresql-contrib
        - libpq-dev
      update_cache: true
      state: present
  - name: Create database user
    become: yes
    become_user: postgres
    postgresql_user:
      user: '{{db_user_name}}'
      password: '{{db_passwd}}'
      encrypted: yes
      role_attr_flags: SUPERUSER
      state: present
  - name: Create database
    become: yes
    become_user: postgres
    postgresql_db:
      name: '{{db_name}}'
      owner: '{{db_owner}}'
